version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-node-browsers-legacy
    steps:
      - checkout
      - run:
          command: |
            python -m virtualenv env
            source ./env/bin/activate
            python -m pip install --upgrade pip
            python -m pip install --upgrade setuptools
            python -m pip install pelican markdown ghp-import
            ./build.sh
